#!/bin/bash
set -e

echo "=== Building STM32 Firmware ==="
mkdir -p build

# Find the generated startup file
STARTUP_FILE=$(ls src/stm32/board/startup_*.s 2>/dev/null | head -1)
if [ -z "$STARTUP_FILE" ]; then
    echo "Error: No startup file found in src/stm32/board/"
    exit 1
fi

# Assemble startup file (auto-generated by svd2odin)
echo "Assembling startup code..."
arm-none-eabi-as -mcpu=cortex-m4 -mthumb -mfloat-abi=hard -mfpu=fpv4-sp-d16 "$STARTUP_FILE" -o build/startup.o

# Find board directory (same as startup file)
BOARD_DIR=$(dirname "$STARTUP_FILE")

# Assemble interrupt helpers
echo "Assembling interrupt helpers..."
arm-none-eabi-as -mcpu=cortex-m4 -mthumb -mfloat-abi=hard -mfpu=fpv4-sp-d16 "$BOARD_DIR/interrupt_helpers.s" -o build/interrupt_helpers.o

# Compile stubs
echo "Compiling stubs..."
arm-none-eabi-gcc -mcpu=cortex-m4 -mthumb -mfloat-abi=hard -mfpu=fpv4-sp-d16 \
    -c "$BOARD_DIR/stubs.c" -o build/stubs.o

# Clean old object files
rm -f build/main*.o

# Build with Odin (creates multiple .o files)
echo "Compiling Odin code..."
# TODO: -no-rtti flag has issues with runtime.Allocator pulling in RTTI code
# For now, building with RTTI. File size impact: ~20-40KB
# -o:size: Optimize for code size (recommended for embedded)
odin build src -target:freestanding_arm32 -microarch:cortex-m4 \
    -no-crt -o:size -build-mode:obj -out:build/main \
    -vet -disallow-do

# Find the generated linker script
LINKER_SCRIPT=$(ls src/stm32/board/STM32*.ld 2>/dev/null | head -1)
if [ -z "$LINKER_SCRIPT" ]; then
    echo "Error: No linker script found in src/stm32/board/"
    exit 1
fi

# Link all object files (using auto-generated linker script)
echo "Linking..."
arm-none-eabi-ld -T "$LINKER_SCRIPT" \
    build/startup.o \
    build/interrupt_helpers.o \
    build/main.o \
    build/stubs.o \
    -L/usr/lib/gcc/arm-none-eabi/14.2.0/thumb/v7e-m+fp/hard \
    -lgcc \
    -o build/firmware.elf

# Create binary
echo "Creating binary..."
arm-none-eabi-objcopy -O binary build/firmware.elf build/firmware.bin

echo "=== Build complete ==="
ls -lh build/firmware.bin
arm-none-eabi-size build/firmware.elf
